docker macos

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -12,10 +12,26 @@ jobs:
     steps:
     - uses: actions/checkout@v3
    
-    - name: setup-docker
-      uses: docker-practice/actions-setup-docker@v1
+    - name: Install Docker
+      run: |
+          brew update
+          brew install --cask docker
 
+    - name: Start Docker
+      run: open --background -a Docker
 
+    - name: Wait for Docker to start
+      run: |
+          timeout=$((SECONDS+60))
+          while ! docker info >/dev/null 2>&1; do
+              if [ $SECONDS -gt $timeout ]; then
+                  echo "Docker failed to start."
+                  exit 1
+              fi
+              sleep 1
+          done
+          
+    
     - name: Build and run Docker image
       run: |
           docker build -t selenium-tests .
